# Generated by Django 4.2 on 2023-04-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField(max_length=25)),
                ('income_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField(max_length=25)),
                ('income_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeToCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin_app.category')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin_app.income')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ManyToManyField(through='fin_app.IncomeToCategory', to='fin_app.category'),
        ),
        migrations.CreateModel(
            name='CostsToCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin_app.category')),
                ('costs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin_app.costs')),
            ],
        ),
        migrations.AddField(
            model_name='costs',
            name='category',
            field=models.ManyToManyField(through='fin_app.CostsToCategory', to='fin_app.category'),
        ),
    ]
