# Generated by Django 4.2 on 2023-04-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costs',
            old_name='name',
            new_name='summa',
        ),
    ]
