# Generated by Django 4.2 on 2023-05-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app', '0004_rename_income_date_costs_cost_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='summa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='summa',
            field=models.FloatField(),
        ),
    ]
