# Generated by Django 4.2 on 2023-05-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app', '0005_alter_costs_summa_alter_income_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
