# Generated by Django 4.2 on 2023-05-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app', '0006_alter_income_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='cost_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_date',
            field=models.DateTimeField(),
        ),
    ]
